# S3 classes ===================================================================
# package_version
setOldClass(Classes = class(packageVersion("base")))

# session_info
setOldClass(Classes = "session_info")



# CellCycleMarkers =============================================================
#' `CellCycleMarkers` Class
#'
#' Data provenence information, including the organism and Ensembl release are
#' defined in [metadata()].
#'
#' @family S4 Classes
#' @author Michael Steinbaugh
#' @export
setClass(
    Class = "CellCycleMarkers",
    contains = "DataFrame"
)



# CellTypeMarkers ==============================================================
#' `CellTypeMarkers` Class
#'
#' Data provenence information, including the organism and Ensembl release are
#' defined in [metadata()].
#'
#' @family S4 Classes
#' @author Michael Steinbaugh
#' @export
#'
#' @return `CellTypeMarkers`.
setClass(
    Class = "CellTypeMarkers",
    contains = "DataFrame"
)



# SeuratMarkers ================================================================
# All markers `data.frame`, generated by
# [Seurat::FindAllMarkers()] return and sanitized with
# [sanitizeSeuratMarkers()]. Grouped by `cluster` column. Note that an
# unmodified Seurat markers `data.frame` will error here by design, since it
# doesn't consistently contain Ensembl gene identifiers.

#' `SeuratMarkers` Class
#'
#' Class containing essential elements for Seurat marker analysis.
#'
#' @family S4 Classes
#' @author Michael Steinbaugh
#' @export
#'
#' @slot data `DataFrame`. Sanitized Seurat markers data.
#' @slot GRanges `GRanges`.
#' @slot metadata `list`. Metadata describing how the analysis was performed.
setClass(
    Class = "SeuratMarkers",
    slots = c(
        data = "DataFrame",
        GRanges = "GRanges",
        metadata = "list"
    )
)
